---
title: Configure OEM Information
description: Configures OEM information to contain the Atlas version and the Atlas Discord server
privilege: TrustedInstaller
actions:
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion'
    value: 'EditionSubManufacturer'
    data: 'Atlas Team'
    type: REG_SZ
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion'
    value: 'EditionSubstring'
    data: 'AtlasOS'
    type: REG_SZ
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion'
    value: 'EditionSubVersion'
    data: 'AtlasOS'
    type: REG_SZ
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\OEMInformation'
    value: 'Manufacturer'
    data: 'Atlas Team'
    type: REG_SZ
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\OEMInformation'
    value: 'Model'
    data: 'AtlasOS'
    type: REG_SZ
  - !registryValue: 
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\OEMInformation'
    value: 'SupportURL'
    data: 'https://discord.atlasos.net'
    type: REG_SZ
